// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlLvPMRpAFxWYj6GrjDQU99kTYe29qV7Q',
    appId: '1:721750940347:web:096e53c3e18f9fc1a7e79e',
    messagingSenderId: '721750940347',
    projectId: 'profit-28bd4',
    authDomain: 'profit-28bd4.firebaseapp.com',
    storageBucket: 'profit-28bd4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXz2pNmVs9MrBKv6Ic6h6uFTaL-fXy28g',
    appId: '1:721750940347:android:402d5b1ec6e5255ca7e79e',
    messagingSenderId: '721750940347',
    projectId: 'profit-28bd4',
    storageBucket: 'profit-28bd4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_XHfXGKAp5OOTP81BBfWa1Khzg59jnR4',
    appId: '1:721750940347:ios:4f0cd7540f91fec7a7e79e',
    messagingSenderId: '721750940347',
    projectId: 'profit-28bd4',
    storageBucket: 'profit-28bd4.appspot.com',
    iosBundleId: 'com.example.proFit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_XHfXGKAp5OOTP81BBfWa1Khzg59jnR4',
    appId: '1:721750940347:ios:d28795f11224fa91a7e79e',
    messagingSenderId: '721750940347',
    projectId: 'profit-28bd4',
    storageBucket: 'profit-28bd4.appspot.com',
    iosBundleId: 'com.example.proFit.RunnerTests',
  );
}
